"""init schema

Revision ID: 88ccda948eed
Revises: a19d13f0ac1a
Create Date: 2026-02-27 17:15:31.143393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ccda948eed'
down_revision: Union[str, Sequence[str], None] = 'a19d13f0ac1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_invested', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('market_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_cost >= 0', name='ck_holdings_avg_cost_nonneg'),
    sa.CheckConstraint('market_price >= 0', name='ck_holdings_market_price_nonneg'),
    sa.CheckConstraint('quantity >= 0', name='ck_holdings_quantity_nonneg'),
    sa.CheckConstraint('total_invested >= 0', name='ck_holdings_total_invested_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_holdings_user_symbol')
    )
    op.create_index('ix_holdings_user_symbol', 'holdings', ['user_id', 'symbol'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('BUY', 'SELL', name='transaction_type'), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_transactions_price_pos'),
    sa.CheckConstraint('quantity > 0', name='ck_transactions_quantity_pos'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_user_symbol_ts', 'transactions', ['user_id', 'symbol', 'timestamp'], unique=False)
    op.create_index('ix_transactions_user_ts', 'transactions', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_ts', table_name='transactions')
    op.drop_index('ix_transactions_user_symbol_ts', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_holdings_user_symbol', table_name='holdings')
    op.drop_table('holdings')
    op.drop_table('users')
    # ### end Alembic commands ###
